# Generated by Django 4.2.13 on 2024-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dht', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temphum',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='temphum',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
