# Generated by Django 4.2.13 on 2024-05-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dht', '0003_alter_temphum_humidity_alter_temphum_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temphum',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='temphum',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
